language: go
sudo: false
go:
  - "1.11"
before_install:
  - go get github.com/mattn/goveralls
script:
  - go build
  - go test ./agenda/model/... ./agenda/service/... -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci
